# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-31 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proso_concepts', '0002_add_tag_langs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='concept',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tag',
            name='value',
            field=models.CharField(max_length=200),
        ),
    ]
