# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-04 06:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proso_subscription', '0002_subscription_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='expiration',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
