# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-10 03:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proso_subscription', '0003_auto_featured_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_limit', models.IntegerField(blank=True, default=None, null=True)),
                ('discount_percentage', models.IntegerField()),
                ('code', models.CharField(max_length=100)),
                ('identifier', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='proso_subscription.SubscriptionPlan')),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='discount',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='proso_subscription.DiscountCode'),
        ),
    ]
