# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-14 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proso_feedback', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
