# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 09:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proso_configab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetup',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
