# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-08 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proso_configab', '0003_transfer_probability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='possiblevalue',
            name='probability',
        ),
    ]
