# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-10 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proso_configab', '0004_remove_possiblevalue_probability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentsetup',
            name='content_hash',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterUniqueTogether(
            name='experimentsetup',
            unique_together=set([('content_hash', 'experiment')]),
        ),
        migrations.AlterUniqueTogether(
            name='possiblevalue',
            unique_together=set([('variable', 'value')]),
        ),
    ]
