# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-05 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proso_flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='additional_info',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
