# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-10 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proso_flashcards', '0002_flashcard_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
