# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-01 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proso_flashcards', '0005_category_display_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='disable_open_questions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='restrict_open_questions',
            field=models.BooleanField(default=False),
        ),
    ]
