# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proso_flashcards', '0011_remove_flashcardanswer_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='children_type',
            field=models.CharField(choices=[('c', 'categories'), ('t', 'terms'), ('f', 'flashcards'), ('x', 'contexts')], max_length=1, null=True, verbose_name='Category of'),
        ),
    ]
