# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-10 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proso_flashcards', '0013_move_structure_to_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='children_type',
        ),
        migrations.RemoveField(
            model_name='category',
            name='contexts',
        ),
        migrations.RemoveField(
            model_name='category',
            name='flashcards',
        ),
        migrations.RemoveField(
            model_name='category',
            name='not_in_model',
        ),
        migrations.RemoveField(
            model_name='category',
            name='subcategories',
        ),
        migrations.RemoveField(
            model_name='category',
            name='terms',
        ),
    ]
