# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-13 02:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proso_flashcards', '0015_types_to_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='type',
        ),
    ]
