# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-09 04:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proso_flashcards', '0018_remove_flashcardanswer_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='term_secondary',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashcards_as_secondary', to='proso_flashcards.Term'),
        ),
    ]
