# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proso_models', '0011_auto_variable_answer_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='lang',
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
    ]
