# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 04:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proso_models', '0012_answer_lang'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('table', models.CharField(max_length=100)),
                ('foreign_key', models.CharField(max_length=100)),
                ('language', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('valid', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='itemtype',
            unique_together=set([('model', 'foreign_key'), ('table', 'foreign_key')]),
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proso_models.ItemType'),
        ),
    ]
