# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-08 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proso_models', '0014_auto_item_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='itemrelation',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
