# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-13 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proso_models', '0015_auto_item_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='type',
            field=models.CharField(default='unknown', max_length=10),
            preserve_default=False,
        ),
    ]
