# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-01 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proso_flashcards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedContext',
            fields=[
                ('context_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='proso_flashcards.Context')),
                ('extra_info', models.TextField()),
            ],
            bases=('proso_flashcards.context',),
        ),
        migrations.CreateModel(
            name='ExtendedTerm',
            fields=[
                ('term_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='proso_flashcards.Term')),
                ('extra_info', models.TextField()),
            ],
            bases=('proso_flashcards.term',),
        ),
    ]
